### PR TITLE
Working branch

### PR DESCRIPTION
**Pull request by deikdesign**
This is a homepage from youtube.com

### CODE REVIEW

**Comment by BrittanyBlake** [comment]
### Status: Invalid 🛑 
****
Hi @deikdesign  and @AlanSoto31. This pull request has been marked as invalid because the repository is not professional. It is missing a descriptive README file in this feature branch. You should make sure that your repo looks professional before review.
Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.) 
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).

****
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!
### Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Comment by AlanSoto31** [comment]
We added a README file accordingly to the requirements

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
# Status: Changes requested :red_circle: 

## Hello @deikdesign and @AlanSoto31 :wave: 

## Your clone looks very nice, I really like it. However, I still need you to change somethings before we move on, alright? Here are my recommendations:

# Page Structure

### Nav Bar

- [ ] Your Youtube logo is not an embedded image, currently it's an icon with a < p > tag. I need you to change that, it should be an embedded < img > ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/navbar_logo_requirement.png));

### Video

- [ ] You need a share < button >, currently it's also an icon with a < p > tag ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png))

- [ ] Your page looks awesome, it's very close to the current YouTube page. But please don't get me wrong, you need to copy [this one](http://archive.vn/Bss88). So I need you to change the section below your video:

## Yours:

Screenshot from 2020-08-17 16-42-54

## Original:

Screenshot from 2020-08-17 16-42-14


# General

- [ ] Your README file needs a screenshot, please provide it one, so that it looks even more professional :wink: 

- [ ] Your Pull Request needs some improvements, change its title and description, add more details to them.

- [ ] Make sure you resolve the conflict you have with the master branch.

## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Review by expjazz — APPROVED** [review]
## Status: Project Approved :clap: 

Great work on implementing the changes requested by my colleague :ok_hand: 

You can go ahead to the next project. 

#### Do not forget to fix the conflict you have in this branch.

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Pull request merged**
